services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
      POSTGRES_DB: book_db
    volumes:
      - /Users/dimit/Desktop/Fax/Semestar 6/EMT/Laboratory Tasks/Lab1/views.sql:/docker-entrypoint-initdb.d/views.sql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./views.sql:/docker-entrypoint-initdb.d/views.sql
    ports:
      - "2345:5432"
volumes:
  pgdata:


